### ISSUE TITLE
Please Add main back to Q1

### ISSUE THREAD

**Issue by JoshInnis** [Prasad4742/Bitnine-Coding-Test#1]

**Comment by Prasad4742** [comment]
Added main to problem 1 and made the code to direct run in cpp compiler

**Comment by Prasad4742** [comment]
also the last output 2 is given wrong in the question itself, as 4th fibonacci number is should be 5. I have verified thoroghly. please also have a look on the question. 
Thank you.

**Comment by Prasad4742** [comment]
Could you please recheck problem 1
